### ISSUE TITLE
Issue Encountered While Trying to Follow Bacter Tutorial

### ISSUE THREAD

**Issue by ditzyyp** [CompEvol/BACTER#35]
I have been trying to follow the tutorial for using Bacter, which is found at [https://tgvaughan.github.io/bacter/doc/basic_tutorial.html ](https://tgvaughan.github.io/bacter/doc/basic_tutorial.html ) with Bacter version 3.0.1 and Beast2 version 2.7. However, when I try to run my XML file with Beast, I encounter the following error:

```
java.lang.IllegalArgumentException: Only one of taxon and alignment should be specified, not both (id=TaxonSet.1).
	at beast.base.evolution.alignment.TaxonSet.initAndValidate(Unknown Source)
	at beast.base.parser.XMLParser.initBEASTObjects(Unknown Source)
	at beast.base.parser.XMLParser.parse(Unknown Source)
	at beast.base.parser.XMLParser.parseFile(Unknown Source)
	at beastfx.app.beast.BeastMCMC.parseArgs(Unknown Source)
	at beastfx.app.beast.Controller$2.run(Unknown Source)
beast.base.parser.XMLParserException: 
Error 110 parsing the xml input file

validate and intialize error: Only one of taxon and alignment should be specified, not both (id=TaxonSet.1).

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <state id='state' spec='State'>
              <stateNode id='Tree.t:simulated_data_A' spec='bacter.model.SimulatedACG'>
                  <taxonset id='TaxonSet.1' spec='TaxonSet'>

	at beast.base.parser.XMLParser.initBEASTObjects(Unknown Source)
	at beast.base.parser.XMLParser.parse(Unknown Source)
	at beast.base.parser.XMLParser.parseFile(Unknown Source)
	at beastfx.app.beast.BeastMCMC.parseArgs(Unknown Source)
	at beastfx.app.beast.Controller$2.run(Unknown Source)
```
Here is the link to the XML file I created following the tutorial: [https://drive.google.com/drive/folders/1l-3EHqwA79NnGTRiqVrOiPfGf0NdisAJ?usp=sharing](https://drive.google.com/drive/folders/1l-3EHqwA79NnGTRiqVrOiPfGf0NdisAJ?usp=sharing)

**Comment by tgvaughan** [comment]
Hi, it looks like your XML has accrued an additional "TaxonSet" element somehow.  Did you add all of the fasta files simultaneously or one at a time?  It's likely the issue you're seeing is due to a slight deviation from the order of operations specified in the tutorial.  (I've just now verified that following the order precisely does generate a working XML, without the additional TaxonSet element which is causing your problem.)

**Comment by itzy11** [comment]
yes, I add all of the fasta files simultaneously

**Comment by ditzyyp** [comment]
yes, I added all of the fasta files simultaneously, but thank you very much. I will try to repeat it with the correct order of operations specified in the tutorial

**Comment by tgvaughan** [comment]
One thing to be wary of with beauti in general is changing big aspects of the model (eg tree prior) multiple times while setting up the analysis.  Many beauti templates can generate broken XML files if this is done.  (Not saying this is what happened here, but it's another possibility.)
